apiVersion: v1
kind: Pod
metadata:
  name: ${{ values.name }}-access
  labels:
    app: ${{ values.name }}
spec:
  containers:
  - name: sqlite-shell
    image: kegster/sqlite3
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: ${{ values.name }}
