apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}
spec:
  ports:
  - port: 9092
    targetPort: 9092
    name: tcp-client
  - port: 9093
    targetPort: 9093
    name: tcp-controller
  clusterIP: None
  selector:
    app: ${{ values.name }}
