apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ values.name }}
spec:
  serviceName: ${{ values.name }}
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.name }}
  template:
    metadata:
      labels:
        app: ${{ values.name }}
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:23.3
        ports:
        - containerPort: 8123
        - containerPort: 9000
        env:
        - name: CLICKHOUSE_PASSWORD
          value: ${{ values.password }}
        - name: CLICKHOUSE_USER
          value: default
        volumeMounts:
        - name: data
          mountPath: /var/lib/clickhouse
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
