apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.name | dump }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.name | dump }}
  template:
    metadata:
      labels:
        app: ${{ values.name | dump }}
    spec:
      containers:
      - name: app
        image: stefanscherer/whoami
        ports:
        - containerPort: 80
